### ISSUE TITLE
Unexpected hasher runtime performance

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/scionlab#111]
There is a transient error introduced by #95 

File "/home/circleci/repo/scionlab/tests/test_hashers.py", line 109, in test_harden_runtime
    "time_8: %f, time_15: %f" % (time_8, time_15))
AssertionError: False is not true : time_8: 0.111553, time_15: 0.143161

See https://circleci.com/gh/netsec-ethz/scionlab/501

**Comment by matzf** [comment]
It's a stupid test anyway. We can just remove it.
