### ISSUE TITLE
Revisit distribution mechanism for update scripts and scionlab-config script.

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#124]
Current mechanism is rather wacky;
- `scionupgrade.service` downloads `scion_upgrade_script.sh` from scion-coord (!) github master branch
- `scion_upgrade_script.sh` installs:
  - service-files from scion-coord github (diffent source than during installation of the VM!)
  - `scionlab-config` from scionlab github

This needs to be cleaned up. At least, all the files would have to be in the same repo.

Preferrably, this will all be taken care of by having scionlab debian packages.
Otherwise, it might be a good option to serve these files from the scionlab-coordinator instance instead of from a github branch (so that the version of the files is tied to the running version of the coordinator, simplifying testing procedures).

**Comment by mkowalski** [comment]
Packages released and shipping `scionlab-config`, closing
