### ISSUE TITLE
Cannot connect to host from the Coordinator: configuration not automatically deployed

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#156]
Some hosts cannot be managed from the Coordinator because ssh refuses to connect. Most likely the problem will be just a firewall configuration, thus an email and patience will be sufficient.
This is the list:
- scionlab-1305-hopper (SIDN)

**Comment by mkowalski** [comment]
For these machines I do have connectivity from the office network, but do not from the server network

- 1501-wozniak
- 1402-bhaskara
- 1401-cray
- 1307-ptolemy
- 1305-hopper
- 1204-thompson

Please note this list do not contain machines which are unavailable from both office and server networks.

**Comment by cmeury** [comment]
Connections to all of these hosts except `scionlab-1204-thompson` have have been restored. Reached out to thompson's maintainers multiple times and escalated to our group lead. The same story applies to `scionlab-1203-hawking`

Hopefully this should be resolved fairly soon and I'll be able to close this issue.

**Comment by matzf** [comment]
Configuration deployment push with SSH access has been removed in #313.
