### ISSUE TITLE
Firewall in front of scionlab-1103-mayer

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#159]
There seems to be a corporate firewall in front of `scionlab-1103-mayer` blocking at least ping and SSH from `scionlab-1102-elion`. It is the only affected source, traffic from other SCIONLab machines works properly.

Probably the corporate firewall in front of `scionlab-1103-mayer` is blocking `192.33.92.66/28` but it's not a confirmed cause.

The issue is not caused by local iptables configuration.

Relates-to: #156

**Comment by cmeury** [comment]
I could not determine any SCMP blocking  as of today, closing the issue.
