### ISSUE TITLE
Vagrant provider not set explicitely

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#165]
Currently the Vagrantfile template does not specify provider used, therefore a default one from the OS/user environment will be applied. As we strictly require to use VirtualBox, Vagrantfile should be enforcing this policy.

The current Vagrant file does not work in systems with default provider being libvirt
```
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: ubuntu/xenial64
Address: https://vagrantcloud.com/ubuntu/xenial64
Requested provider: [:libvirt]
```

https://stackoverflow.com/questions/21840883/specify-default-provider-in-vagrantfile#21843623 as a reference

**Comment by FR4NK-W** [comment]
Closed by PR #166
