### ISSUE TITLE
NTP servers not accessible from some networks

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#167]
The following machines cannot reach publicly accessible NTP servers
* `scionlab-1309-ritchie`
* `scionlab-1401-cray`
* `scionlab-1501-wozniak`
* `scionlab-1901-bose`

This is nothing bad per se and in this scenario there are for sure local NTP servers running in the respective networks. We need to contact owners of these machines and get this info.

A live info can be traced [here](http://monit.netsec.inf.ethz.ch/d/x4y3oWIZz/scionlab-hw?orgId=1&panelId=43&fullscreen) - targets with offset exactly `0 ms` are the ones which cannot be reached, output from `ntpq -p` below

```
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 ntp.cc.upv.es   .INIT.          16 u    -   64    0    0.000    0.000   0.000
 ntp2.cc.upv.es  .INIT.          16 u    -   64    0    0.000    0.000   0.000
```

**Comment by mkowalski** [comment]
The only missing node is `scionlab-1901-bose`

**Comment by cmeury** [comment]
All resolved:

* `scionlab-1309-ritchie`: has working NTP
* `scionlab-1401-cray`: switched to htpdate as a suboptimal, but workable alternative
* `scionlab-1501-wozniak`: switched to htpdate as a suboptimal, but workable alternative
* `scionlab-1901-bose`: working NTP server inside the university network
