### ISSUE TITLE
Once we can deploy bwtest server and pingpong, remove manual supervisord

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#178]
In some SCIONLab machines we run `supervisord` manually, keeping a `bwtestserver` and `pingpong` processes. The configuration files are in `$HOME/supervisord-scion-apps`.
Once we have the ability of deploying these services from the Coordinator (like any BS, PS, etc), remove this manual `supervisord`.
For now only the APs run this supervisor configuration.

**Comment by mkowalski** [comment]
I have a strong feeling I have already wiped the supervisord config some time ago. Once #208 gets merged I will configure APs to run BWtester using systemd and finally close this issue here.
