### ISSUE TITLE
Vagrantfile configures NTP without restarting the service

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#188]
The following code is present in the Vagrantfile

```
systemctl enable ntp
echo -e "tinker panic 0\n" >> /etc/ntp.conf
sed -i 's/\(pool .*\)$/\1 minpoll 1 maxpoll 6/g' /etc/ntp.conf
```

There are two issues with this approach
1. we do not explicitly start NTP relying on the fact a default behaviour of the provider is "enabled"
2. we do not restart NTP after changing the configuration

(1) does not affect us right now as the service is started after the installation (`vendor preset: enabled`) but (2) means the settings are applied only after reboot.

The issue should not be visible in most of the cases as it can happen only in the following scenario

- VM gets time desynchronized by any reason; most popular would be either stale CPU (by overcommitting resources) or strange behaviour on some platforms when sleeping the host while VM is running (unconfirmed issue but claimed to exist)
- VM was never rebooted

**Comment by cmeury** [comment]
#314 will make this issue obsolete, closing.
