### ISSUE TITLE
Certificate reissuing on TRC updates

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#194]
When recreating the TRC of an ISD, triggered by mutations of core ASes or updates of core-AS-keys, we currently do NOT actively reissue all the dependent AS certificates.

##### Background
The initial thought behind this was that the automatic certificate reissuing "at runtime" of the ASes would take care of creating new certificate after disseminating the new TRC with the beaconing process. As it later turned out, this does not currently work, and even if it would work we can't make good use of it for SCIONLab;
* the built in reissue process assumes that all ASes are up somewhat reliably, which is not the case for our user-ASes (which can be down for long periods)
* if the running ASes get reissued certificates, the coordinator does not get notified(*). The coordinator will have stale certificates and overwrite the new certificates whenever the AS is redeployed.

(*) unless we put the coordinator into the loop in the core CS somehow, but this seems a bit nasty.

##### Problem
When the TRC version is bumped 

* the AS certificates (for non-core ASes) in `AS.certificate_chain` still refer to the old TRC version
* when the host configuration is generated, the AS now contains a certificate referring to a TRC version that is not contained in the config. 
  We do not keep/distribute a history of the TRC versions, so the core AS also doesn't have this TRC version in the gen/-folder either.
  This configuration only works if the TRC is somewhere accessible in a cache. :boom: 

##### Proposed fix
Explicitly reissue all affected AS certificates in the coordinator whenever the TRC version is updated. This is boring.
Note that requiring to do this will break User-ASes every time a TRC is modified, until they explicitly fetch their configuration. To address this, we can:
* make it visible in the coordinator: "your AS has an outdated configuration, you may need to update by running `scionlab-config`"
* document the behaviour (in the tutorials).

**Comment by juagargi** [comment]
We also have to remember that this must be solved before mid June, as many of the SCIONLab core AS certificates expire then.

**Comment by mkowalski** [comment]
I somehow cannot see a clear step-by-step scenario how to hit this issue

**Comment by matzf** [comment]
@mkowalski
1) In the admin panel:
  * select a core AS and "update core keys", or
  * add or remove a core-AS
2) you may now have a problem; the non-core ASes in this ISD will stop working
  * if you don't redeploy them, they will die after the grace period because they don't have a certificate for the latest TRC version (and can't get one)
  * if you do redeploy them, they still don't have a certificate for the latest TRC, and even worse, they don't even have the TRC version that corresponds to their AS certificate
