### ISSUE TITLE
Border router / SCION services should wait for tun0 interface if needed

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#206]
As a user I need to be sure OpenVPN connection is ready before I start SCION services. As openvpn@client.service finishes activation before the VPN connection is ready, we cannot rely on a simple systemd-service dependency.

Systemd syntax to achieve that is as follows
```
BindsTo=sys-devices-virtual-net-lan0.device
After=sys-devices-virtual-net-lan0.device
```

Related-bug: #190

**Comment by mkowalski** [comment]
The solution is not so straightforward as we do not statically define `tun0` to be the interface, thus we cannot simply hardcode the dependency on the systemd device.

**Comment by matzf** [comment]
C.f. discussion in related PR.
