### ISSUE TITLE
Demote Raspberry PIs to user ASes

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#207]
Currently there is at least one home-grade Raspberry PI running as infrastructure node, i.e. `17-ffaa:0:1102,[192.33.93.166]`.

We should scan both `17-ffaa:0:1102` and `17-ffaa:0:1107` and move all the devices of this class to their own user ASes attached to `17-ffaa:0:1107`.

Afterwards the following has to be done

- scion-tutorials updated in respect to the applications (Raspberry PIs serve as servers for some of the scion applications)
- infrastructure monitoring (scion-ansible repository) has to be updated with new addresses; this is because we have continuous sensor- and imagefetcher executions across scionlab infrastructure

**Comment by cmeury** [comment]
No hosts in these two ASes (and all ASes) seem to be Raspberry PIs. Closing the issue.
