### ISSUE TITLE
User: invitations

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#21]
Add support for (privileged) users sending an invitation (by email) to potential new users. The email should contain a link to a pre-filled registration form.

We can hopefully make use of either of the following libraries:
* https://github.com/bee-keeper/django-invitations (for invitations only)
* https://github.com/bennylope/django-organizations/ (for invitations and a concept of organisations, which we may want to use for quota management)

**Comment by FR4NK-W** [comment]
User privileges could be managed by adding them to the relevant user groups and check permissions using https://django-braces.readthedocs.io/en/stable/access.html#grouprequiredmixin

**Comment by matzf** [comment]
Has never come up again.
