### ISSUE TITLE
Update to Django 3.0

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#221]
Django 3.0 has been released, we should upgrade at some time.
Check that all the apps/plugins are compatible.

**Comment by mkowalski** [comment]
This is currently impossible due to the `django-jsonfield` not being compatible. It requires `django.utils.six` but that has been removed in Django 3.

As `django-jsonfield` recommends not to use it anymore, this should be the path to follow.

**Comment by mkowalski** [comment]
This is currently impossible due to the `django.utils.functional.curry()` being deprecated in favour of `functools.partial()` or `functools.partialmethod`.

Release note: https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by mkowalski** [comment]
This is currently impossible due to the `django-registration` not being compatible. It requires `django.utils.six` but that has been removed in Django 3.

Related-issue: https://github.com/ubernostrum/django-registration/issues/191

**Comment by FR4NK-W** [comment]
Closed by #225
