### ISSUE TITLE
Setting VM name in Vagrantfile fails on Windows

### ISSUE THREAD

**Issue by ekuiter** [netsec-ethz/scionlab#241]
When configuring a SCION AS with Vagrant/VirtualBox on Windows, `vagrant up` fails with the following error:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "14495db6-50ce-40e5-9d25-40e9e64cdac6", "--name", "SCIONLabVM-ffaa:1:cf9"]

Stderr: VBoxManage.exe: error: Could not rename the directory 'C:\Users\Elias\VirtualBox VMs\ubuntu-xenial-16.04-cloudimg-20190411_1581941209641_44662' to 'C:\Users\Elias\VirtualBox VMs\SCIONLabVM-ffaa:1:cf9' to save the settings file (VERR_INVALID_PARAMETER)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3206 of file VBoxManageModifyVM.cpp
```

I suspect this error occurs due to the colons in the AS address `ffaa:1:cf9`, which Windows does not allow in file names. A possible fix would be to use dashes or underscores instead.

As a workaround, I removed the line `vb.name = "SCIONLabVM-ffaa:1:cf9"` from the Vagrantfile.

**Comment by FR4NK-W** [comment]
@ekuiter 
Thanks for reporting this issue.
The Vagrant configurations generated on scionlab.org now fixes this issues, using the filename IA representation:
https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering#formatting-1
