### ISSUE TITLE
scionlab-config: stop services when scionlab-services.txt is received

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#254]
When we receive the configuration from the coordinator, we must disable the previous services for `scionlab.target` and enable the new ones that come in the `scionlab-services.txt` file.
We also have to stop the previous services before we disable them: if we remove services from the list, they are not stopped (they no longer belong to `scionlab.target`).

**Comment by FR4NK-W** [comment]
Fixed as part of #242 : https://github.com/netsec-ethz/scionlab/pull/242/commits/0c2555b5ca08e57fed397bffc0e2ed8ae62e7e98
