### ISSUE TITLE
scionlab-config misbehaving with no longer used nodes

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#270]
This has happened when running `scionlab-config` at scionlab@scionlab-1101-almeida:

```
scionlab@scionlab-1101-almeida:~$ sudo scionlab-config --force
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

tarfile.ReadError: empty file
```

**Comment by matzf** [comment]
As a temporary fix, I've installed an endhost configuration on `scionlab-1101-almeida` by downloading the config tar from the admin panel, `scp` to almeida and installed it with `scionlab-config --tar ...`.

The download link on the admin panel doesn't do the empty configuration check and returned a nice config tar ball. This will also be the behaviour of the API after 272.
