### ISSUE TITLE
Fix sensor server deployment

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#278]
The sensor server (advertised in the tutorials) was running on `scionlab-1102-achache` but is now broken.
The previous setup with local builds, supervisord and some assorted bash scripts should be converted to a more "standard" setup where the server is controlled by a systemd unit.

The setup also contains a whole bunch of python dependencies etc for the sensor data source. This should ideally be packed in a venv or whatever is appropriate. 

The setup for this server is probably too specific to "generic" support for this, so perhaps the best approach to still have some versioning/overview/reproducability might be to pack this configuration into our ansible setup.

**Comment by juagargi** [comment]
Automatically enabling the sensor server service under our only systemd entrypoint `scionlab.target` won't be possible without integration in the Coordinator.
For now, I'm going to manually create a service that *will be enabled* in that machine.
As @matzf mentions, maybe we want to add an ansible playbook for this, to be able to reproduce the deployment.

**Comment by juagargi** [comment]
There is now a systemd service in `/etc/systemd/system/scion-sensorserver.service` controlling the execution. The sensor reader python itself plus the script starting both the sensor reader and the sensor server go application live under `/opt/sensorserver`; there is a virtual environment in that directory.

**Comment by juagargi** [comment]
There is a `README` in `/opt/sensorserver` detailing how to run the service and recreate the virtual environment.

**Comment by juagargi** [comment]
Now there is an entry in our scionlab-docs wiki
https://gitlab.inf.ethz.ch/PRV-PERRIG/scionlab-docs/-/wikis/home

**Comment by matzf** [comment]
All done here.
