### ISSUE TITLE
Extension of SCIONLab coordinator with User Attachment Point feature

### ISSUE THREAD

**Issue by fl99kl** [netsec-ethz/scionlab#286]
Add a feature to allow users to modify their AS in the SCIONLab so they can serve as an Attachment Point and therefore allow other users to connect to it. 
This includes implementing an option in the SCIONLab to be an AP. If selected the User AP should automatically pull the configuration from the coordinator and then regularly send pull requests to the coordinator (e.g. every 5 seconds). Other ASes should then be able to select them as their AP from the list and connect to them after pulling their new configuration from the coordinator. This results in the following requirements:
User APs need to be labeled in the list. Also only available User APs will be displayed so this needs to be checked regularly.
ASes should be able to see its  connections and the status of the associated User AP.
User AP should not be allowed to use its child as an AP.
User AP should not be able to change its ISD.

This allows to split the issue into two separate projects with the following requirements:
1. Pull attachment points
It's planned that a systemd timer will be used to trigger a script that sends the pull requests, periodically.
It also is foreseen that pull requests will replace push requests entirely. Thus the systemd timer will run on both, the infrastructure and the User APs

2. User attachment points:
User APs will be listed like infrastructure APs in the attachment point model of the django database. 
As Attachment Points will continuously send pull requests to the coordinator that model can be extended by a TimeField that will be updated every time a pull request is received by the coordinator.
If the difference between this TimeField and the current time is bigger than a certain threshhold we can tell that the AP is not active anymore and filter it from the choice list in case it is an User AP.

UI mockups of the planned Front-End changes (User-AP label will be replaced with the label of the respective User AP):
![become AP collapsed](https://user-images.githubusercontent.com/57622392/90116838-646ccf80-dd56-11ea-91bc-40e0df7fcc47.PNG)
![become AP section](https://user-images.githubusercontent.com/57622392/90116841-65056600-dd56-11ea-84bd-8244c3e576cb.PNG)
![AP selection](https://user-images.githubusercontent.com/57622392/86764465-584f6d00-c048-11ea-975a-2c565927352a.png)

**Comment by matzf** [comment]
Thanks for the write up. Some comments:

* we can't use (only) cron for scheduling the polls; cron has a granularity of one minute and we want to poll at intervals of something like 1 to 10s. We can either:
    - use a systemd timer, or
    - add a "daemon" mode to the `scionlab-config` script itself which does the polling (in python). This still requires a systemd unit file to run the daemon.

    The systemd units would also provide a simple way to set this up for the users; the unit files are installed with the package, but disabled by default. If a user wants to run an attachment point, she would just have to do something like `systemctl enable --now scionlab-config.timer`.

* >  If the difference between this TimeField and the current time is bigger than a certain threshhold we can tell that the AP is not active anymore and delete it in case it is an User AP.

   Not delete it, but filter it from the choice list. Handle the case of other user ASes already using the unavailable attachment point by displaying the disabled option value.

* In the mock up, the "Become Attachment point" checkbox is in the wrong place; this "card" where the checkbox is in contains _per link_ settings. Maybe the best place would be just below the "Installation type" options.

   Somewhat related, do we need any additional settings/options for user attachment points? E.g.
   * Which IP address will be used by the connecting user ASes?
   * Will user attachments offer VPN? Always, or optionally?

* Should we show the owners user name (== email address) for user attachment points?

**Comment by matzf** [comment]
Implemented in #306
