### ISSUE TITLE
Flat configuration directory hierarchy

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#307]
Related to https://github.com/scionproto/scion/pull/3877

## Goals
Make the gen/ directory structure flatter to make it easier to navigate. Avoid the replication of topology.json, certs, keys etc. in per-service configuration subdirectories, to allow straight-forward manipulation of e.g. the topology configuration.

#### Current hierarchy:
```
/etc/scion
├── gen
│   ├── ISD17
│   │   └── ASffaa_1_c45
│   │       ├── br17-ffaa_1_c45-1
│   │       │   ├── certs/
│   │       │   ├── keys/
│   │       │   └── topology.json
│   │       │   ├── br.toml
│   │       ├── cs17-ffaa_1_c45-1
│   │       │   ├── certs/
│   │       │   ├── keys/
│   │       │   └── topology.json
│   │       │   ├── cs.toml
│   │       │   ├── beacon_policy.yaml
│   │       └── endhost
│   │           ├── certs/
│   │           ├── sd.toml
│   │           └── topology.json
│   ├── dispatcher
│   │   └── disp.toml
│   └── scionlab-config.json
├── gen-certs/
├── sig.json    # from scion-sig package
└── sig.toml    #  "
```

#### Proposed structure:
```
/etc/scion
├── certs/
├── keys/
├── topology.json
├── br-1.toml
├── cs-1.toml
├── sd.toml
├── disp.toml   # static, add to scion-dispatcher package?
├── beacon_policy.yaml
├── scionlab-config.json  # new: contains list of files added by scionlab-config, with checksum
├── gen-certs/
├── sig.json    # from scion-sig package
└── sig.toml    # from scion-sig package
```

* the root `/etc/scion` contains all `*.toml` service configuration files, the `topology.json` file and the `certs/`, `keys/` (and in the future `crypto/`)
* the `scionlab-config.json` file now contains a list of files generated by the coordinator, with checksum. This allows the `scionlab-config` script to know which files to remove/replace in an update. Also, the checksum allows the `scionlab-config` script to avoid trampling over files modified by the user.
* the `scionlab-config.json` file also contains a list of "managed" services, see https://github.com/netsec-ethz/scionlab/issues/298#issuecomment-688707922.
* the systemd unit files can be simplifed and the "scion-systemd-wrapper" is not needed anymore. E.g. currently the unit `scion-border-router@17-ffaa_1_c45-1.service` will parse the part after the `@` to find the file `/etc/scion/ISD17/ASffaa_1_c45/br17-ffaa_1_c45/br.toml` . With the flat structure, we can just use `scion-border-router@br-1.service` which would use the file `/etc/scion/br-1.toml`.

**Comment by cmeury** [comment]
I sometimes see people deploying different configurations for testing in parallel. For example, deploying a generated topology ISD1 to hook up two nodes with each other. With the current structure, this can be done easily: `/etc/scion/gen/ISD17` and `/etc/scion/gen/ISD1` live happily next to each other. I wonder whether one additional level might still make sense to run thing sin parallel and also to quickly identify the IA (`/etc/scion/17-ASffaa_1_c45`).

**Comment by matzf** [comment]
My idea was to make the default with a single AS case as simple as possible. This is also the (only) difference to the structure proposed in the scionproto/scion "topogen", where a per-AS subdirectory is used. I was thinking we'd omit this level for the sake of brevity.

However, I agree that there should be nothing _preventing_ intermediate or advanced users from re-shuffling the configuration to run multiple ASes in parallel. As some changes to the configuration are required anyway (e.g. default addresses would clash), I think it should be fair to expect that these users manage to move the files around and update the file paths in the config too.
So perhaps what I suggested for the systemd units would be too restrictive. Maybe we could very generically interpret the systemd unit "instance name" (i.e. the part after the '@') as a file path to the configuration file (relative to `/etc/scion` i guess). E.g. `scion-border-router@br-1.service` would point to `/etc/scion/br-1.toml`, and e.g. `scion-border-router@ASff00_1_c45/br-1.service` loads `/etc/scion/ASff00_1_c45/br-1.toml`.

**Comment by cmeury** [comment]
Uh, I like that approach. Keep it simple for the general case, while allowing customization. 👍 

Sidenote for future us: This will break `roles/telegraf_scionlab/tasks/scion_services.yml` in `scionlab-ansible`, but we'll be phasing out telegraf anyway.
