### ISSUE TITLE
scion apps can't be built normally

### ISSUE THREAD

**Issue by Memtwo** [netsec-ethz/scionlab#326]
golangci-lint can't work normally

vagrant@scionlab-ffaa-1-dca:~$ sudo su
root@scionlab-ffaa-1-dca:/home/vagrant# ls
scion-apps
root@scionlab-ffaa-1-dca:/home/vagrant# cd scion-apps/
root@scionlab-ffaa-1-dca:/home/vagrant/scion-apps# make setup_lint
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.26.0
golangci/golangci-lint info checking GitHub for tag 'v1.26.0'
golangci/golangci-lint info found version: 1.26.0 for v1.26.0/linux/amd64
golangci/golangci-lint info installed /root/go/bin/golangci-lint
root@scionlab-ffaa-1-dca:/home/vagrant/scion-apps# make
golangci-lint not found. Install it manually or by running 'make setup_lint'.
Makefile:37: recipe for target 'lint' failed
make: *** [lint] Error 1

**Comment by marcfrei** [comment]
Hi Mewtwo,

it seems that the GOPATH's bin subdirectory is not included in the PATH environment variable. You can add it with the following command

```
export PATH=$PATH:$(go env GOPATH)/bin
```

If you want to make this persistent you could do the following

```
echo >> ~/.profile
echo 'export PATH=$PATH:'$(go env GOPATH)/bin >> ~/.profile
```

Thanks,
Marc
