### ISSUE TITLE
Can we users inject packets to test transmission performance

### ISSUE THREAD

**Issue by Memtwo** [netsec-ethz/scionlab#338]
the packets in bwtester is created automatically. Can I inject packets to test transmission performance via other ways?
And which code file describe the scion header formats?

**Comment by marcfrei** [comment]
> the packets in bwtester is created automatically. Can I inject packets to test transmission performance via other ways?

Unfortunately, there is currently no way to let the bwtester send custom data, see also https://github.com/netsec-ethz/scion-apps/issues/175

> And which code file describe the scion header formats?

For the SCION header specification, please refer to
    https://scion.docs.anapaya.net/en/latest/protocols/scion-header.html

To learn how SCION packets can be serialized and deserialized in Go, see
    https://github.com/scionproto/scion/blob/master/go/lib/slayers/doc.go

**Comment by Memtwo** [comment]
> > the packets in bwtester is created automatically. Can I inject packets to test transmission performance via other ways?
> 
> Unfortunately, there is currently no way to let the bwtester send custom data, see also [netsec-ethz/scion-apps#175](https://github.com/netsec-ethz/scion-apps/issues/175)
> 
> > And which code file describe the scion header formats?
> 
> For the SCION header specification, please refer to
> https://scion.docs.anapaya.net/en/latest/protocols/scion-header.html
> 
> To learn how SCION packets can be serialized and deserialized in Go, see
> https://github.com/scionproto/scion/blob/master/go/lib/slayers/doc.go

Thanks!But which Go code file define the SCION header?

**Comment by marcfrei** [comment]
That would be https://github.com/scionproto/scion/blob/master/go/lib/slayers/scion.go
