### ISSUE TITLE
Check python3 version in scionlab-config

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/scionlab#348]
scionlab-config json.loads the config file without decoding it: https://github.com/netsec-ethz/scionlab/blob/e371775c053195b927644bf2360fb5b0a4012033/scionlab/hostfiles/scionlab-config#L211

Check for python3 version >= 3.6 since this and other constructs used were introduced in python3.6 (https://docs.python.org/3/whatsnew/3.6.html#json), and display an error message otherwise (or rewrite code using features introduced in python3.6 and later).

**Comment by matzf** [comment]
Fair point, we don't explicitly test this in < 3.6, so it's definitely possible we use incompatible stuff.

However, as far as I can tell, this particular example is not problematic. Note that `f` is a file in text mode (same line, with context):
https://github.com/netsec-ethz/scionlab/blob/e371775c053195b927644bf2360fb5b0a4012033/scionlab/hostfiles/scionlab-config#L210-L211
The documentation does not mention any changes for files in text mode. I've just quickly tested this (only this! not the full scionlab-config script) in python 3.5 and it appears to work as expected.

**Comment by matzf** [comment]
Alright, I only saw the context for this issue now (conversation in matrix #dev channel), sorry; you were of course right, but the offending bit is _the other_ `json.load` call here in `_read_config_info`:
https://github.com/netsec-ethz/scionlab/blob/e371775c053195b927644bf2360fb5b0a4012033/scionlab/hostfiles/scionlab-config#L623, when called from here: https://github.com/netsec-ethz/scionlab/blob/e371775c053195b927644bf2360fb5b0a4012033/scionlab/hostfiles/scionlab-config#L612-L613
