### ISSUE TITLE
public_ip is a tuple, probably should be a str?

### ISSUE THREAD

**Issue by code-review-doctor** [netsec-ethz/scionlab#407]
I think this should not have the comma suffix:

https://github.com/netsec-ethz/scionlab/blob/9c16791c78593036006013f19c1253b70dc08ef3/scionlab/forms/attachment_conf_form.py#L81

the comma suffix makes it a tuple. 

Looking at the PortMap, it looks like `ip` should be a `str`: https://github.com/netsec-ethz/scionlab/blob/9c16791c78593036006013f19c1253b70dc08ef3/scionlab/util/portmap.py#L84

If I'm right please let me know and I will do a PR to fix :)

**Comment by matzf** [comment]
Hi @code-review-doctor, thank you for pointing this out.
Indeed, this a mistake and should be fixed, I'll happily accept your PR.

Interestingly, the logic is still functioning correctly despite this mistake. In this bit here we only check for collisions, using `public_ip`  as the key for a dictionary. As we use the tuple for the `public_ip` in all instances, the collisions are still detected as expected. The tests also seem to cover this functionality sufficiently and don't need to be updated.
