### ISSUE TITLE
scionlab.org responding with 502

### ISSUE THREAD

**Issue by sarcasticadmin** [netsec-ethz/scionlab#456]
Im unable to get to https://www.scionlab.org/ and receiving a 502:

![Screenshot_20240507-152957](https://github.com/netsec-ethz/scionlab/assets/30531572/786f4123-36ea-4bae-a7d0-c061d668c1dd)

**Comment by juagargi** [comment]
Can you try again? It loads okay for me from different network points.
The `bad gateway` error could have happened due to a temporary problem of the network (or host-container communication).

**Comment by sarcasticadmin** [comment]
Thanks @juagargi for the follow up, it works now. I reported this on 5/7 after checking from 2 different networks in the US: ATT and TMobile

Anything in the host logs that was give an indication of a problem?

**Comment by juagargi** [comment]
It seems we had an update and the docker container was down for a moment.
