### ISSUE TITLE
User: adapt user model

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#5]
Adapt the default user model to:
* use email instead of a username for login etc.
* only ask for email during registration
* ~~add an organisation field~~ (probably not: we might be able to use e.g. https://github.com/bennylope/django-organizations/ if we want to do this; see also #21)

Adapt the `django_registration.forms.RegistrationForm` and the corresponding template (depends #3).

See notes on extending django user model:
* https://stackoverflow.com/questions/37332190/django-login-with-email/43209322#43209322
* https://www.fomfus.com/articles/how-to-use-email-as-username-for-django-authentication-removing-the-username

**Comment by matzf** [comment]
Clarify: Do we actually want to do this?

**Comment by FR4NK-W** [comment]
No necessarily, but we need at least to extend the auth_user model to include attributes like "AS creation quota" and so on.

**Comment by matzf** [comment]
I just realized that we're currently asking for a username during registration. That needs to be removed.
