### ISSUE TITLE
OpenVPN: add UDP/TCP server configuration

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#60]
Currently have (manually configured) servers that use UDP/TCP setup; two openvpn servers one UDP, one TCP, both handing using the same address range for VPN addresses, using an address-learn-script to explicitly set routing rules per client.
We'll need this, or something similar again to have "no UDP" fallback.

**Comment by matzf** [comment]
@juagargi @FR4NK-W Can we "go live" without this? 

As a (much) simpler emergency solution, would it make sense to serve OpenVPN on multiple ports to have a better chance that one option works through a dumb firewall? I think we could implement this using some simple iptables NAT rules.

**Comment by juagargi** [comment]
Yes, I would postpone this until our initial release.

**Comment by matzf** [comment]
Thankfully, this was never requested back.
