### ISSUE TITLE
Data Migration: assessment

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#64]
Check that current configuration can be adequately represented in new data model. Determine the required steps to import the data into the new coordinator & create issues.

Infrastructure:
  * SCION config
  * VPNs
    * Note: we don't need to migrate the configuration of the point-to-point VPNs used e.g. to connect to GEANT into the data model.

Coordinator:
 * User meta data
 * User ASes
 * ?

**Comment by juagargi** [comment]
I have a first draft on https://github.com/netsec-ethz/scionlab/wiki/Data-migration
Still I'd need to check the viability / effort of the technical side of things:
- what do we use to read scion-web and old coordinator?
- is this "robust" way how we want to proceed? is it robust enough?

Not in the scope of this issue:
- How do we update the automatically updated VMs?
- And the dedicated systems?
