### ISSUE TITLE
Data Migration: configuration verification

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#76]
Create script to compare generated configuration tar-ball with existing `gen/`-folders.

* Sort topology.json, yaml files etc.
* toml files?
* supervisor files *will* have differences, maybe just ignore them

**Comment by matzf** [comment]
@juagargi is this already done? Or anyway are we rather confident enough that the config is reasonably identical?

**Comment by juagargi** [comment]
I've only manually checked some _complicated_ ASes (1-11, 1.13, 42-7, ...) and they where okay. I think we could add some test cases to our integration test to cover for this.
Let's keep the issue open until we check all infrastructure.

**Comment by juagargi** [comment]
At the moment we are checking the configuration as we deploy the hosts in the infrastructure ASes. Since this is a one time thing, we won't need to replicate the test again (the test is just whether it works or not).
