### ISSUE TITLE
Data Migration: enter infrastructure topology

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scionlab#77]
Create a script that creates the data model representation for the existing SCIONLab *infrastructure* topology (somewhat analogous to the current `fixtures/testtopo.py`).

This should:
* create the AS,es Hosts, Routers/Interfaces/Links, Services (etc)
* import keys/certificates

The idea is to start using the new coordinator to start configuring (some of) the scionlab infrastructure hosts.
The attachment points will not yet be included, but we could still create them as "dummy" entries.
(Let's not bother with the VPN settings yet).

**Comment by juagargi** [comment]
Closed by #86
