### ISSUE TITLE
overlay file missing

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#87]
The file under `gen/overlay` is missing when generating the configuration. Without it, at least the current BS refuses to start.

**Comment by matzf** [comment]
(as previously commented in #88)
We don't need this file; it's completely useless. If i recall correctly, it's only used when running tests to set up dummy interfaces with IPv6 or something like this. We will definitely not need this file anymore once we start using our own start-up scripts; in the meantime we can just patch the scion.sh script to not fail stupidly if it's not there.

**Comment by juagargi** [comment]
Closing. See #88
